controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
home:
    path: /home
    controller: App\Controller\HomeController::homepage
login:
    path: /login
    controller: App\Controller\SecurityController::login
logout:
    path: /logout
    controller: App\Controller\SecurityController::logout
register:
    path: /register
    controller: App\Controller\RegistrationController::register
user_register:
    path: /user_register
    controller: App\Controller\UserRegistrationController::register
adm_register:
    path: /adm_register
    controller: App\Controller\AdminRegistrationController::register
user_dashboard:
    path: /profile/user_dashboard
    controller: App\Controller\UserController::userDashboard
admin_dashboard:
    path: /admin/admin_dashboard
    controller: App\Controller\AdminController::adminDashboard



