controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
home:
    path: /home
    controller: App\Controller\HomeController::homepage
login:
    path: /login
    controller: App\Controller\SecurityController::login
logout:
    path: /logout
    controller: App\Controller\SecurityController::logout
user_register:
    path: /user_register
    controller: App\Controller\UserRegistrationController::register
adm_register:
    path: /adm_register
    controller: App\Controller\AdminRegistrationController::register
user_dashboard:
    path: /profile/user_dashboard
    controller: App\Controller\UserController::userDashboard
user_activities:
    path: /profile/user_activities
    controller: App\Controller\UserController::userActivities
all_activities:
    path: /all_activities
    controller: App\Controller\UserController::allActivities
show_activity:
    path: /profile/show_activity/{id}
    controller: App\Controller\UserController::showActivity
join_activity:
    path: /profile/join_activity/{idActivity}/{tickets_number}/{nameActivity}
    controller: App\Controller\UserController::joinActivity
    methods: [POST]
show_joined_activity:
    path: /profile/show_joined_activity/{id}
    controller: App\Controller\UserController::showJoinedActivity
admin_dashboard:
    path: /admin/admin_dashboard
    controller: App\Controller\AdminController::adminDashboard
show_admin_activities:
    path: /admin/show_admin_activities
    controller: App\Controller\AdminController::showAdminActivities
delete_activity:
    path: /admin/delete_activity/{id}
    controller: App\Controller\ActivityController::deleteActivity
create_activity:
    path: /admin/create_activity
    controller: App\Controller\ActivityController::createActivity
show_activity_reviews:
    path: /show_activity_reviews/{id}
    controller: App\Controller\ActivityController::showActivityReviews
print_activity_reviewForm:
    path: /print_activity_reviewForm/{id}
    controller: App\Controller\ActivityController::printActivityReviewForm
add_activity_review:
    path: /add_activity_review/{id}
    controller: App\Controller\ActivityController::addActivityReview
    methods: [POST]




